ci/auto-updates: Fail if dh-cargo-vendored-sources fails for unknown reasons
We were handling the failure in case XS-Vendored-Sources-Rust changed,
but in case some other failure is happening (like right now in plucky),
then we would have just ignored it.

So instead of relying only on the grep output, check if the dh-cargo
source vendoring tool failed for some other reason and return about.

diff --git a/.github/workflows/auto-updates.yaml b/.github/workflows/auto-updates.yaml
--- a/.github/workflows/auto-updates.yaml
+++ b/.github/workflows/auto-updates.yaml
@@ -54,9 +54,17 @@ jobs:
         run: |
           set -euo pipefail
 
-          VENDORED_SOURCES=$(/usr/share/cargo/bin/dh-cargo-vendored-sources 2>&1 || true)
+          VENDORED_SOURCES=$(/usr/share/cargo/bin/dh-cargo-vendored-sources 2>&1) \
+            || cmd_status=$?
           OUTPUT=$(echo "$VENDORED_SOURCES" | grep ^XS-Vendored-Sources-Rust: || true)
           if [ -z "${OUTPUT}" ]; then
+            if [ "${cmd_status:-0}" -ne 0 ]; then
+              # dh-cargo-vendored-sources failed because of other reason, so let's fail with it!
+              echo "dh-cargo-vendored-sources failed:"
+              echo "${VENDORED_SOURCES}"
+              exit "${cmd_status}"
+            fi
+
             echo "XS-Vendored-Sources-Rust is up to date. No change is needed.";
             exit 0
           fi
